[package]
name = "clone_test"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_cbor = "0.11"
candid = "0.10.13"
rand = "0.8"
ic-agent = "0.13"
tokio = { version = "1.30", features = ["full"] }