[package]
name = "profiles"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.14"
getrandom = "0.3.3"
ic-cdk = "0.18.5"
rand = "0.9.1"
serde = "1.0.219"
serde_derive = "1.0.219"
